BEGIN;
CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA extensions;
SELECT plan(34);

SELECT ok((SELECT prosecdef FROM pg_proc WHERE oid = 'app.create_client_record(uuid, text, text, citext, text, text, text, text, text, text, inet)'::regprocedure), 'private create is security definer');
SELECT ok((SELECT prosecdef FROM pg_proc WHERE oid = 'app.update_client_record(uuid, uuid, integer, text, text, citext, text, text, text, text, text, text, inet)'::regprocedure), 'private update is security definer');
SELECT ok((SELECT prosecdef FROM pg_proc WHERE oid = 'app.link_client_portal_user(uuid, uuid, uuid, integer, text, text, text, inet)'::regprocedure), 'private link is security definer');
SELECT ok((SELECT prosecdef FROM pg_proc WHERE oid = 'app.unlink_client_portal_user(uuid, uuid, integer, text, text, text, inet)'::regprocedure), 'private unlink is security definer');
SELECT ok((SELECT prosecdef FROM pg_proc WHERE oid = 'app.archive_client_record(uuid, uuid, integer, text, text, text, inet)'::regprocedure), 'private archive is security definer');
SELECT ok((SELECT prosecdef FROM pg_proc WHERE oid = 'public.current_client_record()'::regprocedure), 'public self-read is security definer');
SELECT is((SELECT proconfig FROM pg_proc WHERE oid = 'app.create_client_record(uuid, text, text, citext, text, text, text, text, text, text, inet)'::regprocedure), ARRAY['search_path=""'], 'private create has empty search path');
SELECT is((SELECT proconfig FROM pg_proc WHERE oid = 'public.current_client_record()'::regprocedure), ARRAY['search_path=""'], 'public self-read has empty search path');
SELECT volatility_is('app', 'create_client_record', ARRAY['uuid','text','text','citext','text','text','text','text','text','text','inet']::name[], 'volatile', 'create is volatile');
SELECT volatility_is('app', 'owner_client_record_list', ARRAY['uuid','integer','integer']::name[], 'stable', 'owner list is stable');
SELECT volatility_is('public', 'current_client_record', ARRAY[]::name[], 'stable', 'current client record is stable');
SELECT ok(NOT has_table_privilege('anon', 'app.clients', 'SELECT'), 'anon has no clients select');
SELECT ok(NOT has_table_privilege('authenticated', 'app.clients', 'SELECT'), 'authenticated has no clients select');
SELECT ok(NOT has_table_privilege('service_role', 'app.clients', 'SELECT'), 'service_role has no clients select');
SELECT ok(NOT has_table_privilege('authenticated', 'app.clients', 'INSERT'), 'authenticated has no clients insert');
SELECT ok(NOT has_table_privilege('authenticated', 'app.clients', 'UPDATE'), 'authenticated has no clients update');
SELECT ok(NOT has_table_privilege('authenticated', 'app.clients', 'DELETE'), 'authenticated has no clients delete');
SELECT ok(NOT has_sequence_privilege('authenticated', 'app.client_number_seq', 'USAGE'), 'authenticated has no sequence usage');
SELECT ok(NOT has_sequence_privilege('service_role', 'app.client_number_seq', 'USAGE'), 'service_role has no sequence usage');
SELECT ok(NOT has_function_privilege('authenticated', 'app.create_client_record(uuid, text, text, citext, text, text, text, text, text, text, inet)', 'EXECUTE'), 'authenticated cannot execute private create');
SELECT ok(NOT has_function_privilege('service_role', 'app.create_client_record(uuid, text, text, citext, text, text, text, text, text, text, inet)', 'EXECUTE'), 'service_role cannot execute private create directly');
SELECT ok(NOT has_function_privilege('authenticated', 'app.link_client_portal_user(uuid, uuid, uuid, integer, text, text, text, inet)', 'EXECUTE'), 'authenticated cannot execute private link');
SELECT ok(NOT has_function_privilege('service_role', 'app.current_client_record_for_authenticated_user()', 'EXECUTE'), 'service_role cannot execute private self-read');
SELECT ok(has_function_privilege('authenticated', 'public.current_client_record()', 'EXECUTE'), 'authenticated can execute public self-read');
SELECT ok(NOT has_function_privilege('anon', 'public.current_client_record()', 'EXECUTE'), 'anon cannot execute public self-read');
SELECT ok(NOT has_function_privilege('service_role', 'public.current_client_record()', 'EXECUTE'), 'service_role cannot execute public self-read');
SELECT ok(has_function_privilege('service_role', 'public.server_create_client_record(uuid, text, text, citext, text, text, text, text, text, text, inet)', 'EXECUTE'), 'service_role can execute create gateway');
SELECT ok(has_function_privilege('service_role', 'public.server_update_client_record(uuid, uuid, integer, text, text, citext, text, text, text, text, text, text, inet)', 'EXECUTE'), 'service_role can execute update gateway');
SELECT ok(has_function_privilege('service_role', 'public.server_link_client_portal_user(uuid, uuid, uuid, integer, text, text, text, inet)', 'EXECUTE'), 'service_role can execute link gateway');
SELECT ok(has_function_privilege('service_role', 'public.server_unlink_client_portal_user(uuid, uuid, integer, text, text, text, inet)', 'EXECUTE'), 'service_role can execute unlink gateway');
SELECT ok(has_function_privilege('service_role', 'public.server_archive_client_record(uuid, uuid, integer, text, text, text, inet)', 'EXECUTE'), 'service_role can execute archive gateway');
SELECT ok(NOT has_function_privilege('authenticated', 'public.server_create_client_record(uuid, text, text, citext, text, text, text, text, text, text, inet)', 'EXECUTE'), 'authenticated cannot execute create gateway');
SELECT ok(NOT has_function_privilege('authenticated', 'public.server_owner_client_record_list(uuid, integer, integer)', 'EXECUTE'), 'authenticated cannot execute owner list gateway');
SELECT ok(NOT EXISTS (SELECT 1 FROM pg_policy WHERE polrelid = 'app.clients'::regclass), 'no broad clients table policies exist');

SELECT * FROM finish();
ROLLBACK;
