BEGIN;
CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA extensions;
SELECT plan(32);

SELECT ok((SELECT prosecdef FROM pg_proc WHERE oid = 'app.create_project_record(uuid, uuid, text, character, text, text, date, date, numeric, character, numeric, character, text, text, text, text, text, inet)'::regprocedure), 'private create Project is security definer');
SELECT ok((SELECT prosecdef FROM pg_proc WHERE oid = 'app.change_project_client(uuid, uuid, uuid, integer, text, text, text, inet)'::regprocedure), 'private Client reassignment is security definer');
SELECT ok((SELECT prosecdef FROM pg_proc WHERE oid = 'public.current_client_project_records(integer, integer)'::regprocedure), 'public Client Project list is security definer');
SELECT is((SELECT proconfig FROM pg_proc WHERE oid = 'app.create_project_record(uuid, uuid, text, character, text, text, date, date, numeric, character, numeric, character, text, text, text, text, text, inet)'::regprocedure), ARRAY['search_path=""'], 'private create has empty search path');
SELECT is((SELECT proconfig FROM pg_proc WHERE oid = 'public.current_client_project_record(uuid)'::regprocedure), ARRAY['search_path=""'], 'public Client detail has empty search path');
SELECT volatility_is('app', 'create_project_record', ARRAY['uuid','uuid','text','character','text','text','date','date','numeric','character','numeric','character','text','text','text','text','text','inet']::name[], 'volatile', 'create Project is volatile');
SELECT volatility_is('public', 'current_client_project_records', ARRAY['integer','integer']::name[], 'stable', 'Client Project list is stable');
SELECT ok((SELECT relrowsecurity FROM pg_class WHERE oid = 'app.projects'::regclass), 'projects RLS enabled');
SELECT ok((SELECT relforcerowsecurity FROM pg_class WHERE oid = 'app.projects'::regclass), 'projects RLS forced');
SELECT ok(NOT EXISTS (SELECT 1 FROM pg_policy WHERE polrelid = 'app.projects'::regclass), 'no broad Project policies exist');
SELECT ok(NOT has_table_privilege('anon', 'app.projects', 'SELECT'), 'anon has no Project SELECT');
SELECT ok(NOT has_table_privilege('authenticated', 'app.projects', 'SELECT'), 'authenticated has no direct Project SELECT');
SELECT ok(NOT has_table_privilege('authenticated', 'app.projects', 'INSERT'), 'authenticated has no Project INSERT');
SELECT ok(NOT has_table_privilege('authenticated', 'app.projects', 'UPDATE'), 'authenticated has no Project UPDATE');
SELECT ok(NOT has_table_privilege('authenticated', 'app.projects', 'DELETE'), 'authenticated has no Project DELETE');
SELECT ok(NOT has_table_privilege('service_role', 'app.projects', 'SELECT'), 'service_role has no direct Project SELECT');
SELECT ok(NOT has_table_privilege('authenticated', 'app.project_number_counters', 'SELECT'), 'authenticated has no counter SELECT');
SELECT ok(NOT has_function_privilege('authenticated', 'app.create_project_record(uuid, uuid, text, character, text, text, date, date, numeric, character, numeric, character, text, text, text, text, text, inet)', 'EXECUTE'), 'authenticated cannot execute private create');
SELECT ok(NOT has_function_privilege('service_role', 'app.create_project_record(uuid, uuid, text, character, text, text, date, date, numeric, character, numeric, character, text, text, text, text, text, inet)', 'EXECUTE'), 'service_role cannot execute private create directly');
SELECT ok(NOT has_function_privilege('authenticated', 'app.change_project_client(uuid, uuid, uuid, integer, text, text, text, inet)', 'EXECUTE'), 'authenticated cannot execute private reassignment');
SELECT ok(NOT has_function_privilege('service_role', 'app.generate_project_number()', 'EXECUTE'), 'service_role cannot execute generator directly');
SELECT ok(has_function_privilege('authenticated', 'public.current_client_project_records(integer, integer)', 'EXECUTE'), 'authenticated can execute Client Project list');
SELECT ok(has_function_privilege('authenticated', 'public.current_client_project_record(uuid)', 'EXECUTE'), 'authenticated can execute Client Project detail');
SELECT ok(NOT has_function_privilege('anon', 'public.current_client_project_records(integer, integer)', 'EXECUTE'), 'anon cannot execute Client Project list');
SELECT ok(NOT has_function_privilege('service_role', 'public.current_client_project_records(integer, integer)', 'EXECUTE'), 'service_role cannot execute Client Project list');
SELECT ok(has_function_privilege('service_role', 'public.server_create_project_record(uuid, uuid, text, character, text, text, date, date, numeric, character, numeric, character, text, text, text, text, text, inet)', 'EXECUTE'), 'service_role can execute create gateway');
SELECT ok(has_function_privilege('service_role', 'public.server_change_project_client(uuid, uuid, uuid, integer, text, text, text, inet)', 'EXECUTE'), 'service_role can execute reassignment gateway');
SELECT ok(has_function_privilege('service_role', 'public.server_complete_project_record(uuid, uuid, integer, text, text, text, inet)', 'EXECUTE'), 'service_role can execute complete gateway');
SELECT ok(has_function_privilege('service_role', 'public.server_cancel_project_record(uuid, uuid, integer, text, text, text, text, inet)', 'EXECUTE'), 'service_role can execute cancel gateway');
SELECT ok(has_function_privilege('service_role', 'public.server_archive_project_record(uuid, uuid, integer, text, text, text, inet)', 'EXECUTE'), 'service_role can execute archive gateway');
SELECT ok(NOT has_function_privilege('authenticated', 'public.server_create_project_record(uuid, uuid, text, character, text, text, date, date, numeric, character, numeric, character, text, text, text, text, text, inet)', 'EXECUTE'), 'authenticated cannot execute Owner Project gateway');
SELECT ok(NOT EXISTS (SELECT 1 FROM pg_proc WHERE proname LIKE '%project_assignment%'), 'no Project assignment helpers exist');

SELECT * FROM finish();
ROLLBACK;
