BEGIN;
CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA extensions;
SELECT plan(34);

SELECT ok((SELECT prosecdef FROM pg_proc WHERE oid = 'app.create_project_task(uuid, uuid, text, uuid, uuid, text, text, numeric, boolean, date, date, boolean, text, text, text, inet)'::regprocedure), 'private create task is security definer');
SELECT ok((SELECT prosecdef FROM pg_proc WHERE oid = 'public.current_client_project_tasks(uuid)'::regprocedure), 'public Client task list is security definer');
SELECT is((SELECT proconfig FROM pg_proc WHERE oid = 'app.create_project_task(uuid, uuid, text, uuid, uuid, text, text, numeric, boolean, date, date, boolean, text, text, text, inet)'::regprocedure), ARRAY['search_path=""'], 'private create task has empty search path');
SELECT is((SELECT proconfig FROM pg_proc WHERE oid = 'public.current_client_project_task(uuid)'::regprocedure), ARRAY['search_path=""'], 'public Client task detail has empty search path');
SELECT volatility_is('app', 'create_project_task', ARRAY['uuid','uuid','text','uuid','uuid','text','text','numeric','boolean','date','date','boolean','text','text','text','inet']::name[], 'volatile', 'create task is volatile');
SELECT volatility_is('app', 'update_project_task', ARRAY['uuid','uuid','integer','text','uuid','uuid','text','text','numeric','boolean','date','date','boolean','text','text','text','inet']::name[], 'volatile', 'update task is volatile');
SELECT volatility_is('app', 'archive_project_task', ARRAY['uuid','uuid','integer','text','text','text','inet']::name[], 'volatile', 'archive task is volatile');
SELECT volatility_is('public', 'current_client_project_tasks', ARRAY['uuid']::name[], 'stable', 'Client task list is stable');
SELECT ok(NOT has_table_privilege('anon', 'app.tasks', 'SELECT'), 'anon cannot select tasks');
SELECT ok(NOT has_table_privilege('authenticated', 'app.tasks', 'SELECT'), 'authenticated cannot select tasks directly');
SELECT ok(NOT has_table_privilege('service_role', 'app.tasks', 'SELECT'), 'service_role has no direct task table SELECT');
SELECT ok(NOT has_table_privilege('authenticated', 'app.tasks', 'INSERT'), 'authenticated cannot insert tasks');
SELECT ok(NOT has_table_privilege('authenticated', 'app.tasks', 'UPDATE'), 'authenticated cannot update tasks');
SELECT ok(NOT has_table_privilege('authenticated', 'app.tasks', 'DELETE'), 'authenticated cannot delete tasks');
SELECT ok(NOT has_table_privilege('authenticated', 'app.project_task_number_counters', 'SELECT'), 'authenticated cannot read task counters');
SELECT ok(NOT has_table_privilege('service_role', 'app.project_task_number_counters', 'UPDATE'), 'service_role cannot update task counters directly');
SELECT ok(NOT has_function_privilege('authenticated', 'app.create_project_task(uuid, uuid, text, uuid, uuid, text, text, numeric, boolean, date, date, boolean, text, text, text, inet)', 'EXECUTE'), 'authenticated cannot execute private create');
SELECT ok(NOT has_function_privilege('service_role', 'app.create_project_task(uuid, uuid, text, uuid, uuid, text, text, numeric, boolean, date, date, boolean, text, text, text, inet)', 'EXECUTE'), 'service_role cannot execute private create directly');
SELECT ok(NOT has_function_privilege('authenticated', 'app.generate_project_task_number(uuid)', 'EXECUTE'), 'authenticated cannot execute task-number generator');
SELECT ok(has_function_privilege('authenticated', 'public.current_client_project_tasks(uuid)', 'EXECUTE'), 'authenticated can execute Client task list');
SELECT ok(has_function_privilege('authenticated', 'public.current_client_project_task(uuid)', 'EXECUTE'), 'authenticated can execute Client task detail');
SELECT ok(NOT has_function_privilege('anon', 'public.current_client_project_tasks(uuid)', 'EXECUTE'), 'anon cannot execute Client task list');
SELECT ok(NOT has_function_privilege('service_role', 'public.current_client_project_tasks(uuid)', 'EXECUTE'), 'service_role cannot execute Client task list');
SELECT ok(has_function_privilege('service_role', 'public.server_create_project_task(uuid, uuid, text, uuid, uuid, text, text, numeric, boolean, date, date, boolean, text, text, text, inet)', 'EXECUTE'), 'service_role can execute create task gateway');
SELECT ok(has_function_privilege('service_role', 'public.server_update_project_task(uuid, uuid, integer, text, uuid, uuid, text, text, numeric, boolean, date, date, boolean, text, text, text, inet)', 'EXECUTE'), 'service_role can execute update task gateway');
SELECT ok(has_function_privilege('service_role', 'public.server_archive_project_task(uuid, uuid, integer, text, text, text, inet)', 'EXECUTE'), 'service_role can execute archive task gateway');
SELECT ok(NOT has_function_privilege('authenticated', 'public.server_create_project_task(uuid, uuid, text, uuid, uuid, text, text, numeric, boolean, date, date, boolean, text, text, text, inet)', 'EXECUTE'), 'authenticated cannot execute Owner task gateway');
SELECT is_empty($$ SELECT routine_name FROM information_schema.routines WHERE routine_schema = 'public' AND routine_name IN ('current_staff_project_tasks', 'current_project_manager_project_tasks', 'current_site_supervisor_project_tasks') $$, 'no public staff task RPC exists');
SELECT has_function('public', 'server_complete_project_task', ARRAY['uuid','uuid','integer','text','text','text','text','inet']::name[], 'task completion gateway is implemented in Package 11.5');
SELECT has_function('public', 'server_change_project_task_status', ARRAY['uuid','uuid','integer','app.project_task_status','text','text','text','text','inet']::name[], 'task status workflow gateway is implemented in Package 11.5');
SELECT ok(NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'app' AND tablename = 'tasks' AND policyname ILIKE '%staff%'), 'no staff task RLS policy exists');
SELECT has_table('app', 'task_updates', 'task updates are implemented in Package 11.5');
SELECT ok(NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'app' AND table_name IN ('financial_transactions','ledger_entries','documents')), 'later finance and document objects remain absent');
SELECT ok(pg_get_functiondef('public.current_account()'::regprocedure) NOT ILIKE '%project_manager%access_allowed%true%' AND pg_get_functiondef('public.current_account()'::regprocedure) NOT ILIKE '%site_supervisor%access_allowed%true%', 'current_account does not activate reserved roles');

SELECT * FROM finish();
ROLLBACK;
