BEGIN;
CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA extensions;
SELECT plan(28);

SELECT ok((SELECT prosecdef FROM pg_proc WHERE oid = 'app.assign_project_task(uuid, uuid, uuid, text, text, text, inet)'::regprocedure), 'private assign task is security definer');
SELECT ok((SELECT prosecdef FROM pg_proc WHERE oid = 'public.server_assign_project_task(uuid, uuid, uuid, text, text, text, inet)'::regprocedure), 'public assign gateway is security definer');
SELECT is((SELECT proconfig FROM pg_proc WHERE oid = 'app.assign_project_task(uuid, uuid, uuid, text, text, text, inet)'::regprocedure), ARRAY['search_path=""'], 'private assign has empty search path');
SELECT is((SELECT proconfig FROM pg_proc WHERE oid = 'public.server_remove_project_task_assignment(uuid, uuid, text, text, text, inet)'::regprocedure), ARRAY['search_path=""'], 'remove gateway has empty search path');
SELECT volatility_is('app', 'assign_project_task', ARRAY['uuid','uuid','uuid','text','text','text','inet']::name[], 'volatile', 'assign task is volatile');
SELECT volatility_is('app', 'remove_project_task_assignment', ARRAY['uuid','uuid','text','text','text','inet']::name[], 'volatile', 'remove task assignment is volatile');
SELECT volatility_is('app', 'owner_project_task_assignment_list', ARRAY['uuid','uuid','boolean']::name[], 'stable', 'Owner task assignment list is stable');
SELECT ok(NOT has_table_privilege('anon', 'app.task_assignments', 'SELECT'), 'anon cannot select task assignments');
SELECT ok(NOT has_table_privilege('authenticated', 'app.task_assignments', 'SELECT'), 'authenticated cannot select task assignments directly');
SELECT ok(NOT has_table_privilege('service_role', 'app.task_assignments', 'SELECT'), 'service_role has no direct task assignment SELECT');
SELECT ok(NOT has_table_privilege('authenticated', 'app.task_assignments', 'INSERT'), 'authenticated cannot insert task assignments');
SELECT ok(NOT has_table_privilege('authenticated', 'app.task_assignments', 'UPDATE'), 'authenticated cannot update task assignments');
SELECT ok(NOT has_table_privilege('authenticated', 'app.task_assignments', 'DELETE'), 'authenticated cannot delete task assignments');
SELECT ok(NOT has_function_privilege('authenticated', 'app.assign_project_task(uuid, uuid, uuid, text, text, text, inet)', 'EXECUTE'), 'authenticated cannot execute private assign');
SELECT ok(NOT has_function_privilege('service_role', 'app.assign_project_task(uuid, uuid, uuid, text, text, text, inet)', 'EXECUTE'), 'service_role cannot execute private assign directly');
SELECT ok(has_function_privilege('service_role', 'public.server_assign_project_task(uuid, uuid, uuid, text, text, text, inet)', 'EXECUTE'), 'service_role can execute assign gateway');
SELECT ok(has_function_privilege('service_role', 'public.server_remove_project_task_assignment(uuid, uuid, text, text, text, inet)', 'EXECUTE'), 'service_role can execute remove gateway');
SELECT ok(has_function_privilege('service_role', 'public.server_owner_project_task_assignment_list(uuid, uuid, boolean)', 'EXECUTE'), 'service_role can execute Owner list gateway');
SELECT ok(NOT has_function_privilege('authenticated', 'public.server_assign_project_task(uuid, uuid, uuid, text, text, text, inet)', 'EXECUTE'), 'authenticated cannot execute assign gateway');
SELECT ok(NOT has_function_privilege('authenticated', 'public.server_owner_project_task_assignment_list(uuid, uuid, boolean)', 'EXECUTE'), 'authenticated cannot execute Owner assignment list gateway');
SELECT is_empty($$ SELECT routine_name FROM information_schema.routines WHERE routine_schema = 'public' AND routine_name IN ('current_staff_task_assignments','current_assigned_tasks','current_project_manager_task_assignments','current_site_supervisor_task_assignments','current_client_task_assignments','server_reassign_project_task') $$, 'no staff, Client or reassign task-assignment RPC exists');
SELECT is_empty($$ SELECT routine_name FROM information_schema.routines WHERE routine_schema = 'public' AND routine_name LIKE '%task_update%' $$, 'no task-update RPC exists');
SELECT is_empty($$ SELECT routine_name FROM information_schema.routines WHERE routine_schema = 'public' AND routine_name LIKE '%complete%task%' $$, 'no public task completion RPC exists');
SELECT ok(NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'app' AND tablename = 'task_assignments'), 'no task assignment RLS policies exist');
SELECT ok(pg_get_functiondef('public.current_account()'::regprocedure) NOT ILIKE '%project_manager%access_allowed%true%' AND pg_get_functiondef('public.current_account()'::regprocedure) NOT ILIKE '%site_supervisor%access_allowed%true%', 'current_account does not activate reserved roles');
SELECT ok(pg_get_functiondef('public.current_client_project_tasks(uuid)'::regprocedure) NOT ILIKE '%task_assignments%', 'Client task list does not expose assignments');
SELECT ok(pg_get_functiondef('public.current_client_project_task(uuid)'::regprocedure) NOT ILIKE '%task_assignments%', 'Client task detail does not expose assignments');
SELECT ok(NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'app' AND table_name IN ('task_updates','progress_updates','completion_overrides','notifications','financial_transactions','ledger_entries','documents')), 'task updates, progress, notification and later objects remain absent');

SELECT * FROM finish();
ROLLBACK;
