BEGIN;
CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA extensions;
SELECT plan(35);

SELECT ok((SELECT prosecdef FROM pg_proc WHERE oid = 'app.update_project_task_progress(uuid,uuid,integer,numeric,text,text,text,text,inet)'::regprocedure), 'private progress function is security definer');
SELECT ok((SELECT prosecdef FROM pg_proc WHERE oid = 'app.change_project_task_status(uuid,uuid,integer,app.project_task_status,text,text,text,text,inet)'::regprocedure), 'private status function is security definer');
SELECT ok((SELECT prosecdef FROM pg_proc WHERE oid = 'app.complete_project_task(uuid,uuid,integer,text,text,text,text,inet)'::regprocedure), 'private completion function is security definer');
SELECT ok((SELECT prosecdef FROM pg_proc WHERE oid = 'app.reopen_project_task(uuid,uuid,integer,numeric,text,text,text,text,inet)'::regprocedure), 'private reopen function is security definer');
SELECT ok((SELECT prosecdef FROM pg_proc WHERE oid = 'app.cancel_project_task(uuid,uuid,integer,text,text,text,text,inet)'::regprocedure), 'private cancellation function is security definer');
SELECT is((SELECT proconfig FROM pg_proc WHERE oid = 'app.update_project_task_progress(uuid,uuid,integer,numeric,text,text,text,text,inet)'::regprocedure), ARRAY['search_path=""'], 'private progress function has empty search path');
SELECT is((SELECT proconfig FROM pg_proc WHERE oid = 'public.server_complete_project_task(uuid,uuid,integer,text,text,text,text,inet)'::regprocedure), ARRAY['search_path=""'], 'public completion gateway has empty search path');
SELECT volatility_is('app', 'update_project_task_progress', ARRAY['uuid','uuid','integer','numeric','text','text','text','text','inet']::name[], 'volatile', 'progress workflow is volatile');
SELECT volatility_is('app', 'change_project_task_status', ARRAY['uuid','uuid','integer','app.project_task_status','text','text','text','text','inet']::name[], 'volatile', 'status workflow is volatile');
SELECT volatility_is('app', 'owner_project_task_update_list', ARRAY['uuid','uuid']::name[], 'stable', 'Owner update history list is stable');
SELECT ok(NOT has_table_privilege('authenticated', 'app.task_updates', 'SELECT'), 'authenticated cannot read task updates directly');
SELECT ok(NOT has_table_privilege('authenticated', 'app.task_updates', 'INSERT'), 'authenticated cannot insert task updates directly');
SELECT ok(NOT has_table_privilege('service_role', 'app.task_updates', 'INSERT'), 'service_role cannot insert task updates directly');
SELECT ok(NOT has_table_privilege('service_role', 'app.task_updates', 'DELETE'), 'service_role cannot delete task updates directly');
SELECT ok(NOT has_function_privilege('authenticated', 'app.update_project_task_progress(uuid,uuid,integer,numeric,text,text,text,text,inet)', 'EXECUTE'), 'authenticated cannot execute private progress workflow');
SELECT ok(NOT has_function_privilege('service_role', 'app.update_project_task_progress(uuid,uuid,integer,numeric,text,text,text,text,inet)', 'EXECUTE'), 'service_role cannot execute private progress workflow directly');
SELECT ok(has_function_privilege('service_role', 'public.server_update_project_task_progress(uuid,uuid,integer,numeric,text,text,text,text,inet)', 'EXECUTE'), 'service_role can execute progress gateway');
SELECT ok(has_function_privilege('service_role', 'public.server_change_project_task_status(uuid,uuid,integer,app.project_task_status,text,text,text,text,inet)', 'EXECUTE'), 'service_role can execute status gateway');
SELECT ok(has_function_privilege('service_role', 'public.server_complete_project_task(uuid,uuid,integer,text,text,text,text,inet)', 'EXECUTE'), 'service_role can execute completion gateway');
SELECT ok(has_function_privilege('service_role', 'public.server_reopen_project_task(uuid,uuid,integer,numeric,text,text,text,text,inet)', 'EXECUTE'), 'service_role can execute reopen gateway');
SELECT ok(has_function_privilege('service_role', 'public.server_cancel_project_task(uuid,uuid,integer,text,text,text,text,inet)', 'EXECUTE'), 'service_role can execute cancellation gateway');
SELECT ok(has_function_privilege('service_role', 'public.server_owner_project_task_update_list(uuid,uuid)', 'EXECUTE'), 'service_role can execute Owner update history list gateway');
SELECT ok(NOT has_function_privilege('authenticated', 'public.server_update_project_task_progress(uuid,uuid,integer,numeric,text,text,text,text,inet)', 'EXECUTE'), 'authenticated cannot execute Owner workflow gateway');
SELECT ok(NOT has_function_privilege('authenticated', 'public.server_owner_project_task_update_list(uuid,uuid)', 'EXECUTE'), 'authenticated cannot execute Owner history gateway');
SELECT is_empty($$ SELECT routine_name FROM information_schema.routines WHERE routine_schema = 'public' AND routine_name IN ('current_staff_task_updates','current_assigned_task_updates','current_client_task_updates') $$, 'no Client or staff task-update history RPC exists');
SELECT is_empty($$ SELECT routine_name FROM information_schema.routines WHERE routine_schema = 'public' AND routine_name IN ('server_calculate_project_completion','server_create_progress_update') $$, 'no legacy completion calculation or generic progress-update gateway exists');
SELECT ok(pg_get_functiondef('app.update_project_task_progress(uuid,uuid,integer,numeric,text,text,text,text,inet)'::regprocedure) ILIKE '%require_active_owner_admin%' AND pg_get_functiondef('app.update_project_task_progress(uuid,uuid,integer,numeric,text,text,text,text,inet)'::regprocedure) ILIKE '%for update%', 'progress workflow verifies Owner and locks task');
SELECT ok(pg_get_functiondef('app.complete_project_task(uuid,uuid,integer,text,text,text,text,inet)'::regprocedure) ILIKE '%app.allow_project_task_workflow%' AND pg_get_functiondef('app.complete_project_task(uuid,uuid,integer,text,text,text,text,inet)'::regprocedure) ILIKE '%insert_project_task_update%', 'completion uses trusted workflow context and history insert');
SELECT ok(pg_get_functiondef('app.complete_project_task(uuid,uuid,integer,text,text,text,text,inet)'::regprocedure) NOT ILIKE '%update app.project_milestones%' AND pg_get_functiondef('app.complete_project_task(uuid,uuid,integer,text,text,text,text,inet)'::regprocedure) NOT ILIKE '%update app.project_phases%' AND pg_get_functiondef('app.complete_project_task(uuid,uuid,integer,text,text,text,text,inet)'::regprocedure) NOT ILIKE '%update app.projects%', 'completion does not complete milestone, phase, or Project');
SELECT ok(pg_get_functiondef('app.cancel_project_task(uuid,uuid,integer,text,text,text,text,inet)'::regprocedure) NOT ILIKE '%task_assignments%' AND pg_get_functiondef('app.reopen_project_task(uuid,uuid,integer,numeric,text,text,text,text,inet)'::regprocedure) NOT ILIKE '%task_assignments%', 'cancel and reopen do not alter task assignments');
SELECT ok(pg_get_functiondef('app.archive_project_task(uuid,uuid,integer,text,text,text,inet)'::regprocedure) ILIKE '%status not in (''COMPLETED'', ''CANCELLED'')%' AND pg_get_functiondef('app.archive_project_task(uuid,uuid,integer,text,text,text,inet)'::regprocedure) ILIKE '%active assignments exist%', 'task archive is terminal-only and preserves active-assignment guard');
SELECT ok(NOT EXISTS (SELECT 1 FROM pg_policy WHERE polrelid = 'app.task_updates'::regclass), 'task updates have no broad RLS policy');
SELECT ok(NOT EXISTS (SELECT 1 FROM pg_proc WHERE pronamespace = 'public'::regnamespace AND proname LIKE '%project_manager%task%'), 'no Project Manager task workflow RPC exists');
SELECT ok(NOT EXISTS (SELECT 1 FROM pg_proc WHERE pronamespace = 'public'::regnamespace AND proname LIKE '%site_supervisor%task%'), 'no Site Supervisor task workflow RPC exists');
SELECT ok(NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'app' AND table_name IN ('payments')), 'excluded finance objects remain absent');

SELECT * FROM finish();
ROLLBACK;
