BEGIN;
SELECT plan(44);

SELECT has_table('app','currency_exchanges','currency exchanges table exists');
SELECT columns_are('app','currency_exchanges',ARRAY['id','financial_event_id','source_account_id','destination_account_id','source_amount','source_currency_code','destination_amount','destination_currency_code','exchange_rate_id','rate_base_currency_code','rate_quote_currency_code','rate_value','rate_source','fee_amount','fee_currency_code','fee_account_id','exchange_date','rounding_result','reference'],'currency exchanges has exact approved 19 columns');
SELECT col_type_is('app','currency_exchanges','id','uuid','id is uuid');
SELECT col_type_is('app','currency_exchanges','financial_event_id','uuid','financial event is uuid');
SELECT col_type_is('app','currency_exchanges','source_account_id','uuid','source account is uuid');
SELECT col_type_is('app','currency_exchanges','destination_account_id','uuid','destination account is uuid');
SELECT col_type_is('app','currency_exchanges','source_amount','numeric(20,6)','source amount exact numeric');
SELECT col_type_is('app','currency_exchanges','source_currency_code','character(3)','source currency exact');
SELECT col_type_is('app','currency_exchanges','destination_amount','numeric(20,6)','destination amount exact numeric');
SELECT col_type_is('app','currency_exchanges','destination_currency_code','character(3)','destination currency exact');
SELECT col_type_is('app','currency_exchanges','exchange_rate_id','uuid','exchange rate id uuid');
SELECT col_type_is('app','currency_exchanges','rate_base_currency_code','character(3)','rate base exact');
SELECT col_type_is('app','currency_exchanges','rate_quote_currency_code','character(3)','rate quote exact');
SELECT col_type_is('app','currency_exchanges','rate_value','numeric(30,12)','rate value exact numeric');
SELECT col_type_is('app','currency_exchanges','rate_source','character varying(120)','rate source exact');
SELECT col_type_is('app','currency_exchanges','fee_amount','numeric(20,6)','fee amount exact numeric');
SELECT col_type_is('app','currency_exchanges','fee_currency_code','character(3)','fee currency exact');
SELECT col_type_is('app','currency_exchanges','fee_account_id','uuid','fee account uuid');
SELECT col_type_is('app','currency_exchanges','exchange_date','date','exchange date exact');
SELECT col_type_is('app','currency_exchanges','rounding_result','numeric(20,6)','rounding result exact numeric');
SELECT col_type_is('app','currency_exchanges','reference','character varying(120)','reference exact');
SELECT col_is_pk('app','currency_exchanges','id','id primary key');
SELECT col_has_default('app','currency_exchanges','id','id default exists');
SELECT col_is_unique('app','currency_exchanges','financial_event_id','one exchange per financial event');
SELECT fk_ok('app','currency_exchanges','financial_event_id','app','financial_events','id','financial event FK');
SELECT fk_ok('app','currency_exchanges','source_account_id','app','financial_accounts','id','source account FK');
SELECT fk_ok('app','currency_exchanges','destination_account_id','app','financial_accounts','id','destination account FK');
SELECT fk_ok('app','currency_exchanges','exchange_rate_id','app','exchange_rates','id','exchange rate FK');
SELECT fk_ok('app','currency_exchanges','source_currency_code','app','currencies','code','source currency FK');
SELECT fk_ok('app','currency_exchanges','destination_currency_code','app','currencies','code','destination currency FK');
SELECT fk_ok('app','currency_exchanges','fee_currency_code','app','currencies','code','fee currency FK');
SELECT fk_ok('app','currency_exchanges','fee_account_id','app','financial_accounts','id','fee account FK');
SELECT ok((SELECT pg_get_constraintdef(oid) FROM pg_constraint WHERE conname='currency_exchanges_distinct_accounts_ck') ILIKE '%source_account_id <> destination_account_id%','source and destination accounts differ');
SELECT ok((SELECT pg_get_constraintdef(oid) FROM pg_constraint WHERE conname='currency_exchanges_positive_amounts_ck') ILIKE '%source_amount >%' AND (SELECT pg_get_constraintdef(oid) FROM pg_constraint WHERE conname='currency_exchanges_positive_amounts_ck') ILIKE '%destination_amount >%','source and destination amounts positive');
SELECT ok((SELECT pg_get_constraintdef(oid) FROM pg_constraint WHERE conname='currency_exchanges_distinct_currencies_ck') ILIKE '%source_currency_code <> destination_currency_code%','source and destination currencies differ');
SELECT ok((SELECT pg_get_constraintdef(oid) FROM pg_constraint WHERE conname='currency_exchanges_rate_pair_ck') ILIKE '%rate_base_currency_code <> rate_quote_currency_code%','rate currencies differ');
SELECT ok((SELECT pg_get_constraintdef(oid) FROM pg_constraint WHERE conname='currency_exchanges_rate_value_ck') ILIKE '%rate_value >%','rate value positive');
SELECT ok((SELECT pg_get_constraintdef(oid) FROM pg_constraint WHERE conname='currency_exchanges_fee_ck') ILIKE '%fee_amount =%' AND (SELECT pg_get_constraintdef(oid) FROM pg_constraint WHERE conname='currency_exchanges_fee_ck') ILIKE '%fee_amount >%','zero and positive fee pairs constrained');
SELECT ok((SELECT relrowsecurity AND relforcerowsecurity FROM pg_class WHERE oid='app.currency_exchanges'::regclass),'currency exchanges force RLS');
SELECT ok((SELECT pg_get_functiondef('app.currency_exchanges_trusted_mutation_guard()'::regprocedure)) ILIKE '%CURRENCY_EXCHANGE%' AND (SELECT pg_get_functiondef('app.currency_exchanges_trusted_mutation_guard()'::regprocedure)) ILIKE '%source_currency_code%' AND (SELECT pg_get_functiondef('app.currency_exchanges_trusted_mutation_guard()'::regprocedure)) ILIKE '%destination_currency_code%','subtype guard validates currency exchange integrity');
SELECT ok((SELECT pg_get_functiondef('app.ledger_entries_trusted_insert_guard()'::regprocedure)) ILIKE '%currency_exchange_posting%' AND (SELECT pg_get_functiondef('app.ledger_entries_trusted_insert_guard()'::regprocedure)) ILIKE '%account_transfer_posting%' AND (SELECT pg_get_functiondef('app.ledger_entries_trusted_insert_guard()'::regprocedure)) ILIKE '%project_expense_posting%','ledger guard adds currency exchange context and preserves previous contexts');
SELECT ok(NOT EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='app' AND c.relkind='S' AND c.relname ILIKE '%exchange%number%'),'no exchange-number sequence');
SELECT is_empty($$ SELECT column_name FROM information_schema.columns WHERE table_schema='app' AND table_name='currency_exchanges' AND column_name IN ('project_id','client_id','notes','document_id','status','approved_by','approved_at','created_at','updated_at','version_number','exchange_number') $$,'forbidden currency exchange columns absent');
SELECT ok((SELECT pg_get_constraintdef(oid) FROM pg_constraint WHERE conname='ledger_entries_rate_snapshot_ck') ILIKE '%DERIVED_FROM_CURRENCY_EXCHANGE%','ledger entries allow derived currency-exchange reporting snapshots');

SELECT * FROM finish();
ROLLBACK;
