BEGIN;
SELECT plan(43);

SELECT has_table('app','document_replacements','document replacement history table exists');
SELECT columns_are('app','document_replacements',ARRAY['id','superseded_document_id','replacement_document_id','created_at','created_by'],'replacement table columns exact');
SELECT col_is_pk('app','document_replacements','id','replacement id is primary key');
SELECT fk_ok('app','document_replacements','superseded_document_id','app','documents','id','superseded document FK exists');
SELECT fk_ok('app','document_replacements','replacement_document_id','app','documents','id','replacement document FK exists');
SELECT fk_ok('app','document_replacements','created_by','app','users','id','created-by FK exists');
SELECT ok(EXISTS (SELECT 1 FROM pg_constraint WHERE conname='document_replacements_not_self_ck'), 'self replacement check exists');
SELECT ok(EXISTS (SELECT 1 FROM pg_constraint WHERE conname='document_replacements_superseded_uk'), 'one direct replacement per superseded document');
SELECT ok(EXISTS (SELECT 1 FROM pg_constraint WHERE conname='document_replacements_replacement_uk'), 'one replacement document cannot replace multiple originals');
SELECT ok((SELECT confdeltype='r' FROM pg_constraint WHERE conname='document_replacements_superseded_fk'), 'superseded FK is restrictive');
SELECT ok((SELECT confdeltype='r' FROM pg_constraint WHERE conname='document_replacements_replacement_fk'), 'replacement FK is restrictive');
SELECT ok((SELECT confdeltype='r' FROM pg_constraint WHERE conname='document_replacements_created_by_fk'), 'created-by FK is restrictive');
SELECT ok(EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname='app' AND indexname='document_replacements_replacement_idx'), 'replacement lookup index exists');
SELECT ok((SELECT relrowsecurity FROM pg_class WHERE oid='app.document_replacements'::regclass), 'replacement RLS enabled');
SELECT ok((SELECT relforcerowsecurity FROM pg_class WHERE oid='app.document_replacements'::regclass), 'replacement RLS forced');
SELECT is((SELECT count(*)::integer FROM pg_policies WHERE schemaname='app' AND tablename='document_replacements'),0,'no broad replacement RLS policies');
SELECT has_function('app','document_replacements_guard_history',ARRAY[]::text[],'replacement immutable-history guard exists');
SELECT has_table('app','document_client_access_privacy','document Client lifecycle privacy table exists');
SELECT columns_are('app','document_client_access_privacy',ARRAY['document_id','privacy_reason','created_at','created_by'],'lifecycle privacy table columns exact');
SELECT col_is_pk('app','document_client_access_privacy','document_id','lifecycle privacy document id is primary key');
SELECT fk_ok('app','document_client_access_privacy','document_id','app','documents','id','lifecycle privacy document FK exists');
SELECT fk_ok('app','document_client_access_privacy','created_by','app','users','id','lifecycle privacy created-by FK exists');
SELECT ok(EXISTS (SELECT 1 FROM pg_constraint WHERE conname='document_client_access_privacy_reason_ck'), 'lifecycle privacy reason check exists');
SELECT ok((SELECT confdeltype='r' FROM pg_constraint WHERE conname='document_client_access_privacy_document_fk'), 'lifecycle privacy document FK is restrictive');
SELECT ok((SELECT confdeltype='r' FROM pg_constraint WHERE conname='document_client_access_privacy_created_by_fk'), 'lifecycle privacy created-by FK is restrictive');
SELECT ok((SELECT relrowsecurity FROM pg_class WHERE oid='app.document_client_access_privacy'::regclass), 'lifecycle privacy RLS enabled');
SELECT ok((SELECT relforcerowsecurity FROM pg_class WHERE oid='app.document_client_access_privacy'::regclass), 'lifecycle privacy RLS forced');
SELECT is((SELECT count(*)::integer FROM pg_policies WHERE schemaname='app' AND tablename='document_client_access_privacy'),0,'no broad lifecycle privacy RLS policies');
SELECT has_function('app','document_client_access_privacy_guard',ARRAY[]::text[],'lifecycle privacy guard exists');
SELECT has_function('app','document_business_context',ARRAY['uuid'],'business context helper exists');
SELECT has_function('app','document_is_superseded',ARRAY['uuid'],'superseded helper exists');
SELECT has_function('app','document_is_client_lifecycle_private',ARRAY['uuid'],'Client lifecycle-private helper exists');
SELECT has_function('app','document_replacement_would_cycle',ARRAY['uuid','uuid'],'cycle helper exists');
SELECT has_function('app','document_is_finalized_from_clean_scan',ARRAY['uuid'],'clean-finalized helper exists');
SELECT has_function('app','owner_restore_document_metadata',ARRAY['uuid','uuid','text'],'restore function exists');
SELECT has_function('app','owner_declare_document_replacement',ARRAY['uuid','uuid','uuid','text'],'replacement declaration function exists');
SELECT has_function('app','owner_document_lifecycle_history',ARRAY['uuid','uuid'],'lifecycle history function exists');
SELECT has_function('public','server_owner_restore_document_metadata',ARRAY['uuid','uuid','text'],'restore service gateway exists');
SELECT has_function('public','server_owner_declare_document_replacement',ARRAY['uuid','uuid','uuid','text'],'replacement service gateway exists');
SELECT has_function('public','server_owner_document_lifecycle_history',ARRAY['uuid','uuid'],'history service gateway exists');
SELECT ok((SELECT pg_get_functiondef('app.owner_archive_document_metadata(uuid,uuid)'::regprocedure)) ILIKE '%document_archived%', 'archive function logs approved action');
SELECT ok((SELECT pg_get_functiondef('app.authorize_document_access(uuid,uuid,text,text)'::regprocedure)) ILIKE '%document_is_superseded%', 'standard document access is supersession-aware');
SELECT ok((SELECT pg_get_functiondef('app.authorize_document_image_access(uuid,uuid,text,text)'::regprocedure)) ILIKE '%document_is_superseded%', 'image derivative access is supersession-aware');

SELECT * FROM finish();
ROLLBACK;
