Foreground yes
User clamav
DatabaseDirectory /var/lib/clamav
PidFile /run/clamav/clamd.pid
LocalSocket /run/clamav/clamd.ctl
LocalSocketGroup clamav
LocalSocketMode 660
FixStaleSocket yes
LogFile /var/log/clamav/clamd.log
LogFileUnlock yes
LogFileMaxSize 5M
LogTime yes
ExitOnOOM yes
ReadTimeout 10
CommandReadTimeout 5
SendBufTimeout 5
MaxThreads 4
MaxConnectionQueueLength 8
StreamMaxLength 25M
MaxFileSize 25M
MaxScanSize 100M
ScanArchive yes
