Foreground yes
DatabaseDirectory /var/lib/clamav
DatabaseOwner clamav
PidFile /run/clamav/freshclam.pid
UpdateLogFile /var/log/clamav/freshclam.log
LogFileMaxSize 5M
LogTime yes
DatabaseMirror database.clamav.net
ScriptedUpdates yes
Checks 12
NotifyClamd /etc/clamav/clamd.conf
